config/routes.rb
Rails.application.routes.draw do
  resources :posts

  root 'home#index'

  get 'home/about' => 'home#about'

  get 'home/about/edit' => 'home#editAbout'

  put 'home/about/save' => 'home#saveAbout'

  get 'home/contact' => 'home#contact'

  get 'home/contact/edit' => 'home#editContact'

  put 'home/contact/save' => 'home#saveContact'

  get 'home/login' => 'home#logIn'

end

app/models/my_info.rb
class MyInfo < ActiveRecord::Base
	validates :name, presence: true
	validates :content, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected
  	def authenticate
  		auth = authenticate_or_request_with_http_basic do |username, password|
        # Fix for deployed version 
        # to use Heroku ENV variables
        userName = defined?(USERNAME) != nil ? USERNAME : ENV['USERNAME']
        pass = defined?(PASSWORD) != nil ? PASSWORD : ENV['PASSWORD']

  			username == userName && password == pass	
  		end

  		session[:authenticated] = auth if auth === true
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	before_action :authenticate, only: [:editAbout, :saveAbout, :editContact, :saveContact]

	def index
		@posts = Post.order(created_at: :desc)
	end

	def about
		@myInfo = MyInfo.find_by(name: "About")
	end

	def editAbout
		@myInfo = MyInfo.find_by(name: "About") || MyInfo.new
	end

	def saveAbout
		if saveInfo?
			redirect_to home_about_path
		else
			render :editAbout
		end
	end

	def contact
		@myInfo = MyInfo.find_by(name: "Contact")
	end

	def editContact
		@myInfo = MyInfo.find_by(name: "Contact") || MyInfo.new
	end

	def saveContact
		if saveInfo?
			redirect_to home_contact_path
		else
			render :editContact
		end
	end

	def logIn
		if (session[:authenticated] != true)
				redirect_to :root if authenticate === true
		else
			redirect_to :root
		end
	end

	private 
		def myinfo_params
			params.require(:my_info).permit(:name, :content)
		end

		def saveInfo?
			@myInfo = MyInfo.find_by(name: myinfo_params[:name])
			@edited = false;

			if @myInfo then
				@edited = @myInfo.update(myinfo_params)
			else
				@myInfo = MyInfo.new(myinfo_params)
				@edited = @myInfo.save
			end
		end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate

	def new
		@post = Post.new
	end

	def edit
		@post = Post.find(params[:id])
	end

	def create
		@post = Post.new(post_params)

		if @post.save
			redirect_to :root
		else
			render :new
		end
	end

	def update
		@post = Post.find(params[:id])

		if @post.update(post_params)
			redirect_to :root
		else
			render :edit
		end
	end

	def destroy
		@post = Post.find(params[:id])
		@post.destroy

		redirect_to :root
	end

	private
		def post_params
			params.require(:post).permit(:title, :body)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def loggedIn?
		session[:authenticated] === true
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/home/about.html.erb
<div class="page-header">
	<h1><%= Constants::ABOUT_TITLE %></h1>
</div>

<div><%= @myInfo && simple_format(@myInfo.content).html_safe %></div>

<% if (loggedIn?) %>
	<div class="page-footer">
		<button class="btn btn-large btn-primary" onclick="window.location = '<%= home_about_edit_path %>'"><%= Constants::EDIT_ABOUT_BUTTON %></button>
	</div>
<% end %>

app/views/home/contact.html.erb
<div class="page-header">
	<h1><%= Constants::CONTACT_TITLE %></h1>
</div>

<div><%= @myInfo && simple_format(@myInfo.content).html_safe %></div>

<% if (loggedIn?) %>
	<div class="page-footer">
		<button class="btn btn-large btn-primary" onclick="window.location = '<%= home_contact_edit_path %>'"><%= Constants::EDIT_CONTACT_BUTTON %></button>
	</div>
<% end %>

app/views/home/editAbout.html.erb
<div class="page-header">
	<h1><%= Constants::EDIT_ABOUT_TITLE %></h1>
</div>

<%= render partial: 'partials/infoForm', locals: { path: home_about_save_path, name: "About" } %>

app/views/home/editContact.html.erb
<div class="page-header">
	<h1><%= Constants::EDIT_CONTACT_TITLE %></h1>
</div>

<%= render partial: 'partials/infoForm', locals: { path: home_contact_save_path, name: "Contact" } %>

app/views/home/index.html.erb
<div class="blog-header">
	<h1 class="blog-title"><%= Constants::BLOG_TITLE %></h1>
    <p class="lead blog-description"><%= Constants::BLOG_DESCRIPTION %></p>
</div>

<div class="blog-main">
	<% @posts.each do |post|  %>
	<!-- /.blog-post -->	
	<div class="blog-post">

		<h2 class="blog-post-title"><%= post.title %></h2>

		<p class="blog-post-meta"><%= post.created_at.strftime("%d %B %Y") %></p>

		<%= simple_format(post.body).html_safe %>

		<% if (loggedIn?) %>
			<div class="page-footer">
				<%= button_to Constants::EDIT_BLOG_BUTTON, edit_post_path(post), method: :get, 
					class: "btn btn-large btn-primary" %>
				<%= button_to Constants::DELETE_BLOG_BUTTON, post_path(post), method: :delete, 
				   data: { confirm: "Are you sure?" }, class: "btn btn-large btn-danger" %>
			</div>
		<% end %>
	</div>

	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
  <title><%= Constants::PAGE_TITLE %></title>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
	<div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="<%= root_path %>"><%= Constants::PAGE_TITLE %></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav pull-right nav-pills">
            <% if (loggedIn?) %>
              <li class="active"><button class="btn btn-primary navbar-btn" 
                onclick="window.location='/posts/new'"><%= Constants::NEW_POST_BUTTON %></button></li>
            <% end %>
            <% if not (loggedIn?) %>
              <li><button class="btn btn-default navbar-btn" onclick="window.location = '/home/login'"><%= Constants::ADMIN_BUTTON %></button></li>
            <% end %>
            <li><button class="btn btn-primary navbar-btn" onclick="window.location = '/home/about'"><%= Constants::ABOUT_BUTTON %></button></li>
            <li><button class="btn btn-primary navbar-btn" onclick="window.location = '/home/contact'"><%= Constants::CONTACT_BUTTON %></button></li>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
  </div>

  <div class="container">

    <%= yield %>

  </div><!-- /.container -->

  <div class="footer">
    <p><%= Constants::FOOTER_DESCRIPTION %></p>
    <p>
      <a href="#"><%= Constants::FOOTER_TO_TOP %></a>
    </p>
  </div>

  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
</body>
</html>

app/views/partials/_errors.html.erb
<% if model.errors.any? %>
	<div class="error">
		<ul>
		<% model.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>

<% end %>

app/views/partials/_infoForm.html.erb
<div class="row">

	<%= render partial: 'partials/errors', locals: { model: @myInfo } %>
	
	<%= form_for @myInfo, url: path, method: :put do |f| %>

		<div class="form-group">

			<%= f.label :name %>
			<%= f.text_field :name, { class:'form-control name', readonly: 'readonly', value: name } %>

		</div>

		<div class="form-group">

			<%= f.label :content %>
			<%= f.text_area :content, { class: 'form-control', 
				rows: '10', placeholder: 'Enter text' } %>

		</div>

		<%= f.submit Constants::INFO_FORM_BUTTON, class: "btn btn-large btn-primary" %>

	<% end %>
</div>

app/views/partials/_postForm.html.erb
<div class="row">

	<%= render partial: 'partials/errors', locals: { model: @post } %>

	<%= form_for @post, url: path, method: method do |f| %>

		<div class="form-group">

			<%= f.label :title %>
			<%= f.text_field :title, { class:'form-control',
				placeholder: 'Enter title' } %>

		</div>

		<div class="form-group">

			<%= f.label :body %>
			<%= f.text_area :body, { class: 'form-control',  
				rows: '20', placeholder: 'Enter body' } %>

		</div>

		<%= f.submit Constants::POST_FORM_BUTTON, class: "btn btn-large btn-primary" %>

	<% end %>

</div>

app/views/posts/edit.html.erb
<div class="page-header">
	<h1><%= Constants::EDIT_POST_TITLE %></h1>
</div>

<%= render partial: 'partials/postForm', locals: { path: post_path, method: "patch" } %>

app/views/posts/new.html.erb
<div class="page-header">
	<h1><%= Constants::CREATE_POST_TITLE %></h1>
</div>

<%= render partial: 'partials/postForm', locals: { path: posts_path, method: "post" } %>